target-version = "py312"
fix = true
line-length = 120

[lint]
select = ["ALL"]
unfixable = ["UP"]
ignore = [
    "D100",
    "D104",
    "D203",
    "D213",
    "D107",
    "COM812",
    "RUF002",
    "CPY001",
    "RUF003",
    "RUF001",
    "EM101",
    "S311",
    "DTZ005",
]

[lint.per-file-ignores]
"src/migrations/**" = ["INP001"]

[lint.pylint]
max-args = 6
