"""add tables.

Revision ID: 1b90dd6fbe9f
Revises: 2ec01256e1b7
Create Date: 2026-10-08 11:21:19.077389

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b90dd6fbe9f"
down_revision: str | Sequence[str] | None = "2ec01256e1b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column(
            "outbox_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False, comment="Идентификатор"
        ),
        sa.Column("event_type", sa.String(), nullable=False, comment="Тип события"),
        sa.Column("payload", postgresql.JSON(astext_type=sa.Text()), nullable=False, comment="Данные о платеже"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Дата создания"),
        sa.Column("processing_date", sa.DateTime(), nullable=True, comment="Дата обработки"),
        sa.Column("status", sa.String(), nullable=False, comment="Статус операции"),
        sa.PrimaryKeyConstraint("outbox_id"),
        schema="payments",
    )
    op.create_table(
        "payment",
        sa.Column(
            "payment_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Идентификатор платежа",
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False, comment="Сумма"),
        sa.Column("currency", sa.String(), nullable=False, comment="Валюта"),
        sa.Column("description", sa.String(), nullable=True, comment="Описание платежа"),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=False, comment="Метаданные"),
        sa.Column("status", sa.String(), nullable=False, comment="Статус"),
        sa.Column("idempotency_key", sa.UUID(), nullable=False, comment="Ключ идемпотентности"),
        sa.Column("webhook_url", sa.String(), nullable=False, comment="WEBHOOK URL"),
        sa.Column("creation_at", sa.DateTime(), nullable=False, comment="Дата создания"),
        sa.Column("processing_date", sa.DateTime(), nullable=True, comment="Дата обработки"),
        sa.PrimaryKeyConstraint("payment_id"),
        sa.UniqueConstraint("idempotency_key"),
        schema="payments",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment", schema="payments")
    op.drop_table("outbox", schema="payments")
    # ### end Alembic commands ###
