version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:18
    restart: on-failure
    ports:
      - "35432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment -d payments"]
      interval: 3s
      timeout: 3s
      retries: 20

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    container_name: payment-processing-api
    build:
      context: ../
      dockerfile: ./ci/Dockerfile.api
    env_file: ../.env
    depends_on:
      rabbit:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000

  consumer:
    container_name: consumer
    build:
      context: ../
      dockerfile: ./ci/Dockerfile.consumer
    env_file: ../.env
    depends_on:
      rabbit:
        condition: service_healthy

  outbox:
    container_name: outbox-worker
    build:
      context: ../
      dockerfile: ./ci/Dockerfile.outbox
    env_file: ../.env
    depends_on:
      rabbit:
        condition: service_healthy

volumes:
  postgres-data:
    external: true
    name: postgres-data
