FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

COPY ./pyproject.toml /app/pyproject.toml
COPY ./uv.lock /app/uv.lock
COPY ./alembic.ini /app/alembic.ini
COPY ./src /app/src

WORKDIR /app

RUN apt-get update \
    && pip install --upgrade pip \
    && pip install uv \
    && uv sync --no-dev

ENTRYPOINT [ "uv", "run", "alembic", "upgrade", "head" ]
